# Generated by Django 2.1.7 on 2019-04-04 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField(default=0)),
                ('STATUS', models.IntegerField(choices=[(3, 'UKONCZONY'), (4, 'USZKODZONY'), (1, 'ROZPOCZETY'), (0, 'NIEZNANY'), (2, 'OCZEKUJACY')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AlterField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='okladka'),
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ExtraInfo'),
            preserve_default=False,
        ),
    ]
