# Generated by Django 2.1.7 on 2019-04-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190404_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='STATUS',
            field=models.IntegerField(choices=[(3, 'UKONCZONY'), (1, 'ROZPOCZETY'), (0, 'NIEZNANY'), (4, 'USZKODZONY'), (2, 'OCZEKUJACY')], default=0),
        ),
    ]
