# Generated by Django 2.1.7 on 2019-04-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190404_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='info',
        ),
        migrations.AddField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
