# Generated by Django 2.1.7 on 2019-04-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190404_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraOpis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.IntegerField(choices=[(3, 'Ukonczony'), (1, 'Oczekujacy'), (4, 'Uszkodzony'), (0, 'Nieznany'), (2, 'Aktywny')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status',
        ),
        migrations.AddField(
            model_name='game',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ExtraOpis'),
            preserve_default=False,
        ),
    ]
