# Generated by Django 2.1.7 on 2019-04-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190404_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.IntegerField(choices=[(2, 'Horror'), (4, 'Race'), (1, 'Survival-Horror'), (3, 'Survival'), (0, 'Sci-Fi')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='game',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.ExtraInfo'),
        ),
        migrations.DeleteModel(
            name='ExtraOpi',
        ),
    ]
