# Generated by Django 2.1.7 on 2019-04-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190404_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='stat',
            field=models.IntegerField(choices=[(0, 'Sci-Fi'), (4, 'Race'), (2, 'Horror'), (1, 'Survival-Horror'), (3, 'Survival')], default=0),
        ),
    ]
