# Generated by Django 2.1.7 on 2019-04-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_extrainfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
