# Generated by Django 2.1.7 on 2019-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190406_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='info',
        ),
        migrations.AddField(
            model_name='game',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExtraInfo',
        ),
    ]
